// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var services = [
  { category: "Operations", tier: "Operations Audit", price: "$1,050", summary: "One-time deep audit of workflows, tools, and bottlenecks with a prioritized action plan." },
  { category: "Operations", tier: "Systems and Workflow Sprint", price: "$3,900", summary: "2\u20134 week sprint to design and implement streamlined systems and SOPs." },
  { category: "Operations", tier: "Ongoing Strategic Support (Retainer)", price: "$2,000 base + $780/wk", summary: "Fractional operations partner: weekly execution, strategy, and accountability." },
  { category: "Websites", tier: "Starter Site", price: "$750", summary: "Clean, professional single-page website." },
  { category: "Websites", tier: "Growth Site", price: "$1,500", summary: "Multi-page site with lead capture and content strategy." },
  { category: "Websites", tier: "Managed Webmaster Plan", price: "$625/mo", summary: "Ongoing site management. *Available exclusively for existing and prior website customers." },
  { category: "\xC0 la Carte", tier: "Monthly Retainer (A la Carte)", price: "$2,340/mo", summary: "Flexible monthly hours across ops, admin, and project tasks." }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List services and pricing",
  description: "Returns Beth Frankos Freelance service tiers, website packages, and \xE0 la carte pricing.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var contact = {
  business: "Beth Frankos Freelance LLC",
  email: "info@bethfrankos.org",
  website: "https://bffreelance.org",
  bookingUrl: "https://bffreelance.org/book",
  paymentsUrl: "https://bffreelance.org/payments",
  websitesUrl: "https://bffreelance.org/websites",
  social: {
    instagram: "https://www.instagram.com/beth.frankos",
    facebook: "https://www.facebook.com/share/1AgkuwNfDa/"
  },
  inquiryForm: "https://docs.google.com/forms/d/e/1FAIpQLScbXZRCufQdGBA1cxb3vYpKw0mb56yFdb-6u1QwReb8RZwT2w/viewform"
};
var get_contact_info_default = defineTool2({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Returns email, booking URL, payments URL, and social links for Beth Frankos Freelance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/tools/list-testimonials.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var testimonials = [
  {
    author: "Julius Miller",
    role: "Contractor",
    quote: "Beth is so efficient, I can't believe how much she was able to help our team get done in just a few weeks."
  },
  {
    author: "Margot Smith",
    role: "CPA",
    quote: "When I initially contacted Beth my team was on edge and our processes were a mess. She helped us get back on track quickly and with no judgment. I highly recommend working with her."
  },
  {
    author: "Renequa Jones",
    role: "Non-profit leader",
    quote: "Beth got my non-profit 501c3 status in less than 2 weeks and curated prospect lists for grant opportunities. I was shocked we got it that fast, but she made everything simple and easy."
  }
];
var list_testimonials_default = defineTool3({
  name: "list_testimonials",
  title: "List client testimonials",
  description: "Returns published client testimonials for Beth Frankos Freelance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(testimonials, null, 2) }],
    structuredContent: { testimonials }
  })
});

// src/lib/mcp/tools/get-booking-link.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var booking = {
  bookingPage: "https://bffreelance.org/book",
  calendly: "https://calendly.com/bethfrankosfreelance/15min",
  inquiryForm: "https://docs.google.com/forms/d/e/1FAIpQLScbXZRCufQdGBA1cxb3vYpKw0mb56yFdb-6u1QwReb8RZwT2w/viewform",
  description: "Free 15-minute strategy call. The booking page has a short intake form that pre-fills the calendar."
};
var get_booking_link_default = defineTool4({
  name: "get_booking_link",
  title: "Get booking link",
  description: "Returns the Calendly and intake form URLs for booking a free 15-minute strategy call.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(booking, null, 2) }],
    structuredContent: booking
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bffreelance-mcp",
  title: "Beth Frankos Freelance MCP",
  version: "0.1.0",
  instructions: "Public tools for Beth Frankos Freelance LLC. Use `list_services` for tiers and pricing, `get_contact_info` for email and social links, `list_testimonials` for client quotes, and `get_booking_link` for the free strategy call URL.",
  tools: [list_services_default, get_contact_info_default, list_testimonials_default, get_booking_link_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
